name: appsync-darren-${self:custom.stage}
schema: schema.api.graphql
authentication:
  type: AMAZON_COGNITO_USER_POOLS
  config:
    userPoolId: !Ref CognitoUserPool
    awsRegion: ${aws:region}
    defaultAction: ALLOW

logging:
  roleArn: { 'Fn::GetAtt': [ 'AppSyncCloudWatchLogsRole', 'Arn' ] }
  level: 'ALL'  # Set to NONE, ERROR, or ALL
  retentionInDays: 3

substitutions:
  tweetsTable: !Ref TweetsTable

# see https://github.com/sid88in/serverless-appsync-plugin/blob/master/doc/pipeline-functions.md
pipelineFunctions:
  getMyProfile:
    dataSource: usersTable
    code: src/pipelineFunctions/getMyProfile.js

  editMyProfile:
    dataSource: usersTable
    code: src/pipelineFunctions/editMyProfile.js

  getTweets:
    dataSource: tweetsTable
    code: src/pipelineFunctions/getTweets.js

  getMyTimeline:
    dataSource: timelinesTable
    code: src/pipelineFunctions/getMyTimeline.js

  tweetFunction:
    dataSource: tweet

  likeFunction:
    dataSource: like

  unlikeFunction:
    dataSource: unlike

  # Nested Fields
  tweetProfile:
    dataSource: usersTable
    code: src/pipelineFunctions/tweetProfile.js

  likedProfile:
    dataSource: likesTable
    code: src/pipelineFunctions/likedProfile.js

  timelinePageTweets:
    dataSource: tweetsTable
    code: src/pipelineFunctions/timelinePageTweets.js

resolvers:
  Query.getMyProfile:
    functions:
      - getMyProfile

  Query.getTweets:
    functions:
      - getTweets

  Query.getMyTimeline:
    functions:
      - getMyTimeline

  Mutation.editMyProfile:
    functions:
      - editMyProfile

  Mutation.tweet:
    functions:
      - tweetFunction

  Mutation.like:
    functions:
      - likeFunction

  Mutation.unlike:
    functions:
      - unlikeFunction

  # Nested Fields
  Tweet.profile:
    functions:
      - tweetProfile

  Tweet.liked:
    functions:
      - likedProfile

  TimelinePage.tweets:
    functions:
      - timelinePageTweets

dataSources:
  none:
    type: NONE

  usersTable:
    type: AMAZON_DYNAMODB
    description: Users Table
    config:
      tableName: !Ref UsersTable

  tweetsTable:
    type: AMAZON_DYNAMODB
    description: Tweets Table
    config:
      tableName: !Ref TweetsTable

  timelinesTable:
    type: AMAZON_DYNAMODB
    description: Timelines Table
    config:
      tableName: !Ref TimelinesTable

  likesTable:
    type: AMAZON_DYNAMODB
    description: Likes Table
    config:
      tableName: !Ref LikesTable

  tweet:
    type: AWS_LAMBDA
    description: update dynamoDB with changes from new tweet
    config:
      function:
        handler: src/pipelineFunctions/tweet.handler
        environment:
          USERS_TABLE: !Ref UsersTable
          TWEETS_TABLE: !Ref TweetsTable
          TIMELINES_TABLE: !Ref TimelinesTable
        iamRoleStatements:
          - Effect: Allow
            Action:
              - lambda:invokeFunction
            Resource: '*'
          - Effect: Allow
            Action:
              - dynamodb:UpdateItem
            Resource: !GetAtt UsersTable.Arn
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource:
              - !GetAtt TweetsTable.Arn
              - !GetAtt TimelinesTable.Arn

  like:
    type: AWS_LAMBDA
    description: update dynamoDB with changes from like
    config:
      function:
        handler: src/pipelineFunctions/like.handler
        environment:
          LIKES_TABLE: !Ref LikesTable
          TWEETS_TABLE: !Ref TweetsTable
          USERS_TABLE: !Ref UsersTable
        iamRoleStatements:
          - Effect: Allow
            Action:
              - lambda:invokeFunction
            Resource: '*'
          - Effect: Allow
            Action:
              - dynamodb:UpdateItem
            Resource:
              - !GetAtt TweetsTable.Arn
              - !GetAtt UsersTable.Arn
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource:
              - !GetAtt LikesTable.Arn

  unlike:
    type: AWS_LAMBDA
    description: update dynamoDB with changes from unlike
    config:
      function:
        handler: src/pipelineFunctions/unlike.handler
        environment:
          LIKES_TABLE: !Ref LikesTable
          TWEETS_TABLE: !Ref TweetsTable
          USERS_TABLE: !Ref UsersTable
        iamRoleStatements:
          - Effect: Allow
            Action:
              - lambda:invokeFunction
            Resource: '*'
          - Effect: Allow
            Action:
              - dynamodb:UpdateItem
            Resource:
              - !GetAtt TweetsTable.Arn
              - !GetAtt UsersTable.Arn
          - Effect: Allow
            Action:
              - dynamodb:DeleteItem
            Resource:
              - !GetAtt LikesTable.Arn